- .scalafmt.conf
- .travis.yml
- build.sbt
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/HttpApiV0.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/defs/AssetsEndpointDefs.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/models/OutputInfo.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/models/TransactionInfo.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/routes/AssetsRoutes.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/services/AssetsService.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/services/TransactionsService.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/queries/AssetQuerySet.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/repositories/AssetRepo.scala
- modules/explorer-core/src/test/scala/org/ergoplatform/explorer/db/models/generators.scala
- modules/explorer-core/src/test/scala/org/ergoplatform/explorer/db/repositories/AssetRepoSpec.scala
Close #3 
Repo:
Add REST API calls:
> Get issued tokens info

- modules/chain-grabber/src/main/scala/org/ergoplatform/explorer/db/models/aggregates/FlatBlock.scala
- modules/chain-grabber/src/main/scala/org/ergoplatform/explorer/grabber/ChainGrabber.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/HttpApiV0.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/services/AddressesService.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/services/AssetsService.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/services/BlockChainService.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/services/DexService.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/services/OffChainService.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/Err.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/models/BlockInfo.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/repositories/OutputRepo.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/package.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/protocol/dex.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/protocol/utils.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/services/ErgoNetworkService.scala
- modules/explorer-core/src/test/scala/org/ergoplatform/explorer/db/repositories/OutputRepoSpec.scala
- modules/explorer-core/src/test/scala/org/ergoplatform/explorer/db/repositories/TestOutputRepo.scala
- modules/explorer-core/src/test/scala/org/ergoplatform/explorer/services/DexContractsSpec.scala
- project/dependencies.scala
- project/versions.scala
> use compiled DEX sell/buy order contracts

- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/queries/HeaderQuerySet.scala
> Block ids ordering

- modules/chain-grabber/src/main/scala/org/ergoplatform/explorer/db/models/aggregates/FlatBlock.scala
- modules/chain-grabber/src/main/scala/org/ergoplatform/explorer/grabber/ChainGrabber.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/defs/BoxesEndpointDefs.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/models/OutputInfo.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/models/TransactionInfo.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/routes/BoxesRoutes.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/models/Output.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/queries/OutputQuerySet.scala
- TransactionInfo.timestamp semantics fixed
- TransactionInfo.outputs deduplication
> TransactionInfo.timestamp semantics fixed.

- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/commonDirectives.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/defs/BlocksEndpointDefs.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/queries/HeaderQuerySet.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/queries/UInputQuerySet.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/queries/UOutputQuerySet.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/queries/UTransactionQuerySet.scala
- modules/utx-watcher/src/main/scala/org/ergoplatform/explorer/db/models/aggregates/FlatUTransaction.scala
- Correct blocks sorting params mapping
- Some unconfirmed transactions queries fixed
> Minor bug fixes

- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/models/TransactionInfo.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/models/UTransactionInfo.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/queries/AssetQuerySet.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/queries/OutputQuerySet.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/queries/UAssetQuerySet.scala
- Unconfirmed assets deduplication
- Assets deduplication in SQL queries
- Output/ById ordering by `main_chain`
> Assets deduplication

- .scalafmt.conf
- modules/chain-grabber/src/main/resources/logback.xml
- modules/chain-grabber/src/main/scala/org/ergoplatform/explorer/db/models/aggregates/FlatBlock.scala
- modules/chain-grabber/src/main/scala/org/ergoplatform/explorer/grabber/ChainGrabber.scala
- modules/chain-grabber/src/main/scala/org/ergoplatform/explorer/grabber/services/GrabberService.scala
- modules/chain-grabber/src/test/resources/logback.xml
- modules/chain-grabber/src/test/scala/org/ergoplatform/explorer/grabber/ChainGrabberSpec.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/queries/HeaderQuerySet.scala
- modules/explorer-core/src/test/scala/org/ergoplatform/explorer/db/repositories/TransactionRepoSpec.scala
- project/dependencies.scala
- project/versions.scala
> Synchronization bugfix

- build.sbt
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/services/BlockChainService.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/services/TransactionsService.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/models/Transaction.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/queries/OutputQuerySet.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/queries/TransactionQuerySet.scala
> Improvements

- .travis.yml
- modules/chain-grabber/src/main/scala/org/ergoplatform/explorer/db/models/aggregates/FlatBlock.scala
- modules/chain-grabber/src/main/scala/org/ergoplatform/explorer/grabber/services/GrabberService.scala
- modules/chain-grabber/src/test/scala/org/ergoplatform/explorer/grabber/ChainGrabberSpec.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/models/InputInfo.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/models/TransactionInfo.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/models/TransactionSummary.scala
- modules/explorer-core/src/main/resources/db/V1__Node_data.sql
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/models/Input.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/queries/InputQuerySet.scala
- modules/explorer-core/src/test/scala/org/ergoplatform/explorer/db/models/generators.scala
> Inputs indexing.

- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/models/OutputInfo.scala
> OutputInfo extended.

- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/models/TransactionInfo.scala
> `inclusionHeight` added to `TransactionInfo`.

- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/models/TransactionInfo.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/models/TransactionSummary.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/models/Transaction.scala
> Index field added to `TransactionInfo`/`TransactionSummary`.

- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/clients/ergo/ErgoNetworkClient.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/DoobieTrans.scala
> Adaptive master nodes pool

- Readme.md
Adding reference to the ergo-bootstrap project.
> README: add ergo-bootstrap reference

- build.sbt
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/models/Items.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/defs/BoxesEndpointDefs.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/models/AssetInfo.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/models/BoxQuery.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/models/OutputInfo.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/models/TokenInfo.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/routes/BoxesRoutes.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/services/BoxesService.scala
- modules/explorer-core/src/main/resources/db/V7__Schema.sql
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/clients/ergo/ErgoNetworkClient.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/queries/OutputQuerySet.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/queries/UOutputQuerySet.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/queries/package.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/repositories/OutputRepo.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/repositories/UAssetRepo.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/repositories/UDataInputRepo.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/repositories/UInputRepo.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/repositories/UOutputRepo.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/repositories/UTransactionRepo.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/package.scala
- modules/explorer-core/src/test/scala/org/ergoplatform/explorer/db/repositories/TestOutputRepo.scala
- modules/migrator/src/main/scala/org/ergoplatform/explorer/migration/migrations/RegistersAndConstantsMigration.scala
- project/versions.scala
> Complex UTXO queries API

- modules/chain-grabber/src/main/scala/org/ergoplatform/explorer/indexer/Application.scala
- modules/chain-grabber/src/main/scala/org/ergoplatform/explorer/indexer/modules/RepoBundle.scala
- modules/chain-grabber/src/main/scala/org/ergoplatform/explorer/indexer/processes/EpochsIndexer.scala
- modules/chain-grabber/src/test/scala/org/ergoplatform/explorer/indexer/GrabberTestNetworkClient.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/defs/EpochsEndpointDefs.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/routes/DocsRoutes.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/routes/EpochsRoutes.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/routes/RoutesV1Bundle.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/services/Boxes.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/services/Epochs.scala
- modules/explorer-core/src/main/resources/db/V7__Schema.sql
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/clients/ergo/ErgoNetworkClient.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/models/EpochParameters.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/queries/EpochParametersQuerySet.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/repositories/EpochInfoRepo.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/protocol/models/ApiNodeInfo.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/protocol/models/ApiNodeInfoEpochParameters.scala
- project/dependencies.scala
- project/versions.scala
https://github.com/ergoplatform/explorer-backend/issues/98
> Network params api method

- modules/chain-grabber/src/main/scala/org/ergoplatform/explorer/indexer/extractors/blockStats.scala
- modules/chain-grabber/src/main/scala/org/ergoplatform/explorer/indexer/models/TotalParams.scala
- modules/chain-grabber/src/main/scala/org/ergoplatform/explorer/indexer/processes/ChainIndexer.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/queries/BlockInfoQuerySet.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/repositories/BlockInfoRepo.scala
- modules/migrator/src/main/scala/org/ergoplatform/explorer/migration/Application.scala
- modules/migrator/src/main/scala/org/ergoplatform/explorer/migration/migrations/BlockchainStatsMigration.scala
> Blockchain stats bug

- modules/chain-grabber/src/main/resources/application.conf
- modules/chain-grabber/src/main/scala/org/ergoplatform/explorer/indexer/Application.scala
- modules/chain-grabber/src/main/scala/org/ergoplatform/explorer/indexer/processes/ChainIndexer.scala
- modules/chain-grabber/src/main/scala/org/ergoplatform/explorer/indexer/processes/EpochsIndexer.scala
- modules/chain-grabber/src/main/scala/org/ergoplatform/explorer/settings/IndexerSettings.scala
- modules/chain-grabber/src/test/scala/org/ergoplatform/explorer/indexer/ChainGrabberSpec.scala
- modules/chain-grabber/src/test/scala/org/ergoplatform/explorer/indexer/GrabberTestNetwork.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/clients/ergo/ErgoNetworkClient.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/clients/ergo/NodesPool.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/protocol/models/ApiNodeInfo.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/protocol/models/ApiNodeInfoEpochParameters.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/services/ErgoNetwork.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/services/NodesPool.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/services/TxResponse.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/settings/NetworkSettings.scala
- modules/explorer-core/src/test/scala/org/ergoplatform/explorer/services/ErgoNetworkSpec.scala
- modules/explorer-core/src/test/scala/org/ergoplatform/explorer/services/nodeApiGenerator.scala
- modules/utx-broadcaster/src/main/resources/application.conf
- modules/utx-broadcaster/src/main/scala/org/ergoplatform/explorer/broadcaster/Application.scala
- modules/utx-broadcaster/src/main/scala/org/ergoplatform/explorer/broadcaster/UtxBroadcaster.scala
- modules/utx-broadcaster/src/main/scala/org/ergoplatform/explorer/settings/UtxBroadcasterSettings.scala
- modules/utx-tracker/src/main/resources/application.conf
- modules/utx-tracker/src/main/scala/org/ergoplatform/explorer/settings/UtxTrackerSettings.scala
- modules/utx-tracker/src/main/scala/org/ergoplatform/explorer/tracker/Application.scala
- modules/utx-tracker/src/main/scala/org/ergoplatform/explorer/tracker/UtxTracker.scala
> Nodes ranking support added

- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/models/DataInputInfo.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/models/TransactionInfo.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/services/Transactions.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/models/BlockExtension.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/models/aggregates/FullDataInput.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/queries/DataInputQuerySet.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/repositories/DataInputRepo.scala
> Data inputs to APIv1 transaction methods. 

- build.sbt
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/defs/TokensEndpointDefs.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/routes/TokensRoutes.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/services/Tokens.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/queries/TokensQuerySet.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/repositories/TokenRepo.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/package.scala
- project/versions.scala
> GetTokensBySymbol API method added

- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/defs/TransactionsEndpointDefs.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/repositories/UTransactionRepo.scala
added sorting by "size" in apiV0GetTransactionsUnconfirmed
> resolve issue #174

- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/queries/UAssetQuerySet.scala
> Unconfirmed Tokens in getApiV1AddressesP1BalanceTotal - i170 & Unconfirmed balance wrong when a payment is made - i141

- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/defs/BlocksEndpointDefs.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/models/BlockHeader.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/models/BlockPowSolutions.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/routes/BlocksRoutes.scala
- modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/services/Blocks.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/queries/HeaderQuerySet.scala
- modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/repositories/HeaderRepo.scala
getBlockHeaders API method added.
> BlockHeaders EP
